# Generated by Django 4.2.7 on 2024-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="picture_url",
            field=models.CharField(default="", max_length=500),
        ),
    ]
