# Generated by Django 4.2.7 on 2024-09-22 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_equipment_picture_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="email",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="name",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="password",
        ),
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
