# Generated by Django 4.2.7 on 2024-09-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_staff_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="picture_url",
        ),
        migrations.AddField(
            model_name="equipment",
            name="picture",
            field=models.ImageField(
                default="default.jpg", upload_to="equipment_pictures/"
            ),
        ),
    ]
