# Generated by Django 5.1.1 on 2024-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_notification_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinghistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("approved", "approved"),
                    ("denied", "denied"),
                    ("cancelled", "cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
